function letter=cellRead2(value,lan)

if lan==1;
    
    % English Alphabet

if value=='0';
    letter=' ';
elseif value=='1';
    letter='a';
elseif value=='2';
    letter=',';
elseif value=='3';
    letter='b';
elseif value=='4';
    letter='%%';
elseif value=='5';
    letter='k';
elseif value=='6';
    letter=';';
elseif value=='7';
    letter='l';
elseif value=='8';
    letter='%%';
elseif value=='9';
    letter='c';
elseif value=='10';
    letter='i';
elseif value=='11';
    letter='f';
elseif value=='12';
    letter='/';
elseif value=='13';
    letter='m';
elseif value=='14';
    letter='s';
elseif value=='15';
    letter='p';
elseif value=='16';
    letter='%%';
elseif value=='17';
    letter='e';
elseif value=='18';
    letter=':';
elseif value=='19';
    letter='h';
elseif value=='20';
    letter='in';
elseif value=='21';
    letter='o';
elseif value=='22';
    letter='!';
elseif value=='23';
    letter='r';
elseif value=='24';
    letter='%%';
elseif value=='25';
    letter='d';
elseif value=='26';
    letter='j';
elseif value=='27';
    letter='g';
elseif value=='28';
    letter='ar';
elseif value=='29';
    letter='n';
elseif value=='30';
    letter='t';
elseif value=='31';
    letter='q';
elseif value=='32';
    letter='@';
elseif value=='33';
    letter='ch';
elseif value=='34';
    letter='en';
elseif value=='35';
    letter='gh';
elseif value=='36';
    letter='_';
elseif value=='37';
    letter='u';
elseif value=='38';
    letter='"';
elseif value=='39';
    letter='v';
elseif value=='40';
    letter='%%';
elseif value=='41';
    letter='sh';
elseif value=='42';
    letter='ow';
elseif value=='43';
    letter='ed';
elseif value=='44';
    letter='ing';
elseif value=='45';
    letter='x';
elseif value=='46';
    letter='the';
elseif value=='47';
    letter='and';
elseif value=='48';
    letter='&';
elseif value=='49';
    letter='wh';
elseif value=='50';
    letter='.';
elseif value=='51';
    letter='ou';
elseif value=='52';
    letter='"';
elseif value=='53';
    letter='z';
elseif value=='54';
    letter='()';
elseif value=='55';
    letter='of';    
elseif value=='56';
    letter='%%';
elseif value=='57';
    letter='th';
elseif value=='58';
    letter='w';
elseif value=='59';
    letter='er';
elseif value=='60';
    letter='#';
elseif value=='61';
    letter='y';
elseif value=='62';
    letter='with';
elseif value=='63';
    letter='for';
else
    letter='err';    
    
end


elseif lan==2;
    
    % Sinhala Hodiya
    
    
 if value=='0';
    letter=' ';
elseif value=='1';
    letter='w';
elseif value=='2';
    letter='0';
elseif value=='3';
    letter='n';
elseif value=='4';
    letter='x';
elseif value=='5';
    letter='l';
elseif value=='6';
    letter='0';
elseif value=='7';
    letter=',';
elseif value=='8';
    letter='a';
elseif value=='9';
    letter='p';
elseif value=='10';
    letter='b';
elseif value=='11';
    letter='*';
elseif value=='12';
    letter='ft';
elseif value=='13';
    letter='u';
elseif value=='14';
    letter='i';
elseif value=='15';
    letter='m';
elseif value=='16';
    letter='0';
elseif value=='17';
    letter='t';
elseif value=='18';
    letter='[';
elseif value=='19';
    letter='y';
elseif value=='20';
    letter='B';
elseif value=='21';
    letter='Ts';
elseif value=='22';
    letter='0';
elseif value=='23';
    letter='r';
elseif value=='24';
    letter='N';
elseif value=='25';
    letter='o';
elseif value=='26';
    letter='c';
elseif value=='27';
    letter='.';
elseif value=='28';
    letter='wd';
elseif value=='29';
    letter='k';
elseif value=='30';
    letter=';';
elseif value=='31';
    letter='{';
elseif value=='32';
    letter='0';
elseif value=='33';
    letter='P';
elseif value=='34';
    letter='ta';
elseif value=='35';
    letter='>';
elseif value=='36';
    letter='0';
elseif value=='37';
    letter='W';
elseif value=='38';
    letter='0';
elseif value=='39';
    letter='j';
elseif value=='40';
    letter='L';
elseif value=='41';
    letter='I';
elseif value=='42';
    letter='T!';
elseif value=='43';
    letter='v';
elseif value=='44';
    letter='X';
elseif value=='45';
    letter='T';
elseif value=='46';
    letter='O';
elseif value=='47';
    letter='Y';
elseif value=='48';
    letter='0';
elseif value=='49';
    letter='M';
elseif value=='50';
    letter='0';
elseif value=='51';
    letter='W!';
elseif value=='52';
    letter='CO';
elseif value=='53';
    letter='K';
elseif value=='54';
    letter='0';
elseif value=='55';
    letter='we';    
elseif value=='56';
    letter='<';
elseif value=='57';
    letter=':';
elseif value=='58';
    letter='G';
elseif value=='59';
    letter='wE';
elseif value=='60';
    letter='#';
elseif value=='61';
    letter='h';
elseif value=='62';
    letter='g';
elseif value=='63';
    letter='V';
else
    letter='err';    
    
    
end


end



