function letter=cellRead3(value,lan)

if lan==1;
    
    % English Alphabet

if strcmp(value,0);
    letter=' ';
elseif strcmp(value,1);
    letter='a';
elseif strcmp(value,2);
    letter=',';
elseif strcmp(value,3);
    letter='b';
elseif strcmp(value,4);
    letter='%%';
elseif strcmp(value,5);
    letter='k';
elseif strcmp(value,6);
    letter=';';
elseif strcmp(value,7);
    letter='l';
elseif strcmp(value,8);
    letter='%%';
elseif strcmp(value,9);
    letter='c';
elseif strcmp(value,10);
    letter='i';
elseif strcmp(value,11);
    letter='f';
elseif strcmp(value,12);
    letter='/';
elseif strcmp(value,13);
    letter='m';
elseif strcmp(value,14);
    letter='s';
elseif strcmp(value,15);
    letter='p';
elseif strcmp(value,16);
    letter='%%';
elseif strcmp(value,17);
    letter='e';
elseif strcmp(value,18);
    letter=':';
elseif strcmp(value,19);
    letter='h';
elseif strcmp(value,20);
    letter='in';
elseif strcmp(value,21);
    letter='o';
elseif strcmp(value,22);
    letter='!';
elseif strcmp(value,23);
    letter='r';
elseif strcmp(value,24);
    letter='%%';
elseif strcmp(value,25);
    letter='d';
elseif strcmp(value,26);
    letter='j';
elseif strcmp(value,27);
    letter='g';
elseif strcmp(value,28);
    letter='ar';
elseif strcmp(value,29);
    letter='n';
elseif strcmp(value,30);
    letter='t';
elseif strcmp(value,31);
    letter='q';
elseif strcmp(value,32);
    letter='@';
elseif strcmp(value,33);
    letter='ch';
elseif strcmp(value,34);
    letter='en';
elseif strcmp(value,35);
    letter='gh';
elseif strcmp(value,36);
    letter='_';
elseif strcmp(value,37);
    letter='u';
elseif strcmp(value,38);
    letter='"';
elseif strcmp(value,39);
    letter='v';
elseif strcmp(value,40);
    letter='%%';
elseif strcmp(value,41);
    letter='sh';
elseif strcmp(value,42);
    letter='ow';
elseif strcmp(value,43);
    letter='ed';
elseif strcmp(value,44);
    letter='ing';
elseif strcmp(value,45);
    letter='x';
elseif strcmp(value,46);
    letter='the';
elseif strcmp(value,47);
    letter='and';
elseif strcmp(value,48);
    letter='&';
elseif strcmp(value,49);
    letter='wh';
elseif strcmp(value,50);
    letter='.';
elseif strcmp(value,51);
    letter='ou';
elseif strcmp(value,52);
    letter='"';
elseif strcmp(value,53);
    letter='z';
elseif strcmp(value,54);
    letter='()';
elseif strcmp(value,55);
    letter='of';    
elseif strcmp(value,56);
    letter='%%';
elseif strcmp(value,57);
    letter='th';
elseif strcmp(value,58);
    letter='w';
elseif strcmp(value,59);
    letter='er';
elseif strcmp(value,60);
    letter='#';
elseif strcmp(value,61);
    letter='y';
elseif strcmp(value,62);
    letter='with';
elseif strcmp(value,63);
    letter='for';
else
    letter='err';    
    
end


elseif lan==2;
    
    % Sinhala Hodiya
    
    
 if strcmp(value,'0');
    letter=' ';
elseif strcmp(value,'1');
    letter='w';
elseif strcmp(value,'2');
    letter='0';
elseif strcmp(value,'3');
    letter='n';
elseif strcmp(value,'4');
    letter='x';
elseif strcmp(value,'5');
    letter='l';
elseif strcmp(value,'6');
    letter='0';
elseif strcmp(value,'7');
    letter=',';
elseif strcmp(value,'8');
    letter='a';
elseif strcmp(value,'9');
    letter='p';
elseif strcmp(value,'10');
    letter='b';
elseif strcmp(value,'11');
    letter='*';
elseif strcmp(value,'12');
    letter='ft';
elseif strcmp(value,'13');
    letter='u';
elseif strcmp(value,'14');
    letter='i';
elseif strcmp(value,'15');
    letter='m';
elseif strcmp(value,'16');
    letter='0';
elseif strcmp(value,'17');
    letter='t';
elseif strcmp(value,'18');
    letter='[';
elseif strcmp(value,'19');
    letter='y';
elseif strcmp(value,'20');
    letter='B';
elseif strcmp(value,'21');
    letter='Ts';
elseif strcmp(value,'22');
    letter='0';
elseif strcmp(value,'23');
    letter='r';
elseif strcmp(value,'24');
    letter='N';
elseif strcmp(value,'25');
    letter='o';
elseif strcmp(value,'26');
    letter='c';
elseif strcmp(value,'27');
    letter='.';
elseif strcmp(value,'28');
    letter='wd';
elseif strcmp(value,'29');
    letter='k';
elseif strcmp(value,'30');
    letter=';';
elseif strcmp(value,'31');
    letter='{';
elseif strcmp(value,'32');
    letter='0';
elseif strcmp(value,'33');
    letter='P';
elseif strcmp(value,'34');
    letter='ta';
elseif strcmp(value,'35');
    letter='>';
elseif strcmp(value,'36');
    letter='0';
elseif strcmp(value,'37');
    letter='W';
elseif strcmp(value,'38');
    letter='0';
elseif strcmp(value,'39');
    letter='j';
elseif strcmp(value,'40');
    letter='L';
elseif strcmp(value,'41');
    letter='I';
elseif strcmp(value,'42');
    letter='T!';
elseif strcmp(value,'43');
    letter='v';
elseif strcmp(value,'44');
    letter='X';
elseif strcmp(value,'45');
    letter='T';
elseif strcmp(value,'46');
    letter='O';
elseif strcmp(value,'47');
    letter='Y';
elseif strcmp(value,'48');
    letter='0';
elseif strcmp(value,'49');
    letter='M';
elseif strcmp(value,'50');
    letter='0';
elseif strcmp(value,'51');
    letter='W!';
elseif strcmp(value,'52');
    letter='CO';
elseif strcmp(value,'53');
    letter='K';
elseif strcmp(value,'54');
    letter='0';
elseif strcmp(value,'55');
    letter='we';    
elseif strcmp(value,'56');
    letter='<';
elseif strcmp(value,'57');
    letter=':';
elseif strcmp(value,'58');
    letter='G';
elseif strcmp(value,'59');
    letter='wE';
elseif strcmp(value,'60');
    letter='#';
elseif strcmp(value,'61');
    letter='h';
elseif strcmp(value,'62');
    letter='g';
elseif strcmp(value,'63');
    letter='V';
else
    letter='err';    
    
    
end


end



